# Generated by Django 3.1.3 on 2023-04-14 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='is_correct',
            new_name='validation',
        ),
    ]
