# Generated by Django 3.1.3 on 2023-04-14 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230414_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='validation',
            new_name='is_correct',
        ),
    ]
